# CMake generated Testfile for 
# Source directory: /home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/scratch
# Build directory: /home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/cmake-cache/scratch
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-scratch_scratch-simulator "ns3.42-scratch-simulator-default")
set_tests_properties(ctest-scratch_scratch-simulator PROPERTIES  WORKING_DIRECTORY "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_test "ns3.42-test-default")
set_tests_properties(ctest-scratch_test PROPERTIES  WORKING_DIRECTORY "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_test5g "ns3.42-test5g-default")
set_tests_properties(ctest-scratch_test5g PROPERTIES  WORKING_DIRECTORY "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_test_slicing "ns3.42-test_slicing-default")
set_tests_properties(ctest-scratch_test_slicing PROPERTIES  WORKING_DIRECTORY "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_subdir_scratch-subdir "ns3.42-scratch-subdir-default")
set_tests_properties(ctest-scratch_subdir_scratch-subdir PROPERTIES  WORKING_DIRECTORY "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build/scratch/subdir/" _BACKTRACE_TRIPLES "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;109;create_scratch;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
subdirs("nested-subdir")
