# CMake generated Testfile for 
# Source directory: /home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/zigbee/examples
# Build directory: /home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/cmake-cache/src/zigbee/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-zigbee-nwk-direct-join "ns3.42-zigbee-nwk-direct-join-default")
set_tests_properties(ctest-zigbee-nwk-direct-join PROPERTIES  WORKING_DIRECTORY "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build/src/zigbee/examples/" _BACKTRACE_TRIPLES "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/zigbee/examples/CMakeLists.txt;12;build_lib_example;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/zigbee/examples/CMakeLists.txt;0;")
add_test(ctest-zigbee-nwk-association-join "ns3.42-zigbee-nwk-association-join-default")
set_tests_properties(ctest-zigbee-nwk-association-join PROPERTIES  WORKING_DIRECTORY "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build/src/zigbee/examples/" _BACKTRACE_TRIPLES "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/zigbee/examples/CMakeLists.txt;12;build_lib_example;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/zigbee/examples/CMakeLists.txt;0;")
add_test(ctest-zigbee-nwk-routing "ns3.42-zigbee-nwk-routing-default")
set_tests_properties(ctest-zigbee-nwk-routing PROPERTIES  WORKING_DIRECTORY "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build/src/zigbee/examples/" _BACKTRACE_TRIPLES "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/zigbee/examples/CMakeLists.txt;12;build_lib_example;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/zigbee/examples/CMakeLists.txt;0;")
add_test(ctest-zigbee-nwk-routing-grid "ns3.42-zigbee-nwk-routing-grid-default")
set_tests_properties(ctest-zigbee-nwk-routing-grid PROPERTIES  WORKING_DIRECTORY "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build/src/zigbee/examples/" _BACKTRACE_TRIPLES "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/zigbee/examples/CMakeLists.txt;12;build_lib_example;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/zigbee/examples/CMakeLists.txt;0;")
