# CMake generated Testfile for 
# Source directory: /home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/fd-net-device/examples
# Build directory: /home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/cmake-cache/src/fd-net-device/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-dummy-network "ns3.42-dummy-network-default")
set_tests_properties(ctest-dummy-network PROPERTIES  WORKING_DIRECTORY "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/fd-net-device/examples/CMakeLists.txt;3;build_lib_example;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/fd-net-device/examples/CMakeLists.txt;0;")
add_test(ctest-fd2fd-onoff "ns3.42-fd2fd-onoff-default")
set_tests_properties(ctest-fd2fd-onoff PROPERTIES  WORKING_DIRECTORY "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/fd-net-device/examples/CMakeLists.txt;12;build_lib_example;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/fd-net-device/examples/CMakeLists.txt;0;")
add_test(ctest-realtime-dummy-network "ns3.42-realtime-dummy-network-default")
set_tests_properties(ctest-realtime-dummy-network PROPERTIES  WORKING_DIRECTORY "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/fd-net-device/examples/CMakeLists.txt;21;build_lib_example;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/fd-net-device/examples/CMakeLists.txt;0;")
add_test(ctest-realtime-fd2fd-onoff "ns3.42-realtime-fd2fd-onoff-default")
set_tests_properties(ctest-realtime-fd2fd-onoff PROPERTIES  WORKING_DIRECTORY "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/fd-net-device/examples/CMakeLists.txt;31;build_lib_example;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/fd-net-device/examples/CMakeLists.txt;0;")
add_test(ctest-fd-emu-ping "ns3.42-fd-emu-ping-default")
set_tests_properties(ctest-fd-emu-ping PROPERTIES  WORKING_DIRECTORY "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/fd-net-device/examples/CMakeLists.txt;41;build_lib_example;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/fd-net-device/examples/CMakeLists.txt;0;")
add_test(ctest-fd-emu-udp-echo "ns3.42-fd-emu-udp-echo-default")
set_tests_properties(ctest-fd-emu-udp-echo PROPERTIES  WORKING_DIRECTORY "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/fd-net-device/examples/CMakeLists.txt;50;build_lib_example;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/fd-net-device/examples/CMakeLists.txt;0;")
add_test(ctest-fd-emu-onoff "ns3.42-fd-emu-onoff-default")
set_tests_properties(ctest-fd-emu-onoff PROPERTIES  WORKING_DIRECTORY "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/fd-net-device/examples/CMakeLists.txt;59;build_lib_example;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/fd-net-device/examples/CMakeLists.txt;0;")
add_test(ctest-fd-emu-send "ns3.42-fd-emu-send-default")
set_tests_properties(ctest-fd-emu-send PROPERTIES  WORKING_DIRECTORY "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/fd-net-device/examples/CMakeLists.txt;68;build_lib_example;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/fd-net-device/examples/CMakeLists.txt;0;")
add_test(ctest-fd-emu-tc "ns3.42-fd-emu-tc-default")
set_tests_properties(ctest-fd-emu-tc PROPERTIES  WORKING_DIRECTORY "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/fd-net-device/examples/CMakeLists.txt;79;build_lib_example;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/fd-net-device/examples/CMakeLists.txt;0;")
add_test(ctest-fd-tap-ping "ns3.42-fd-tap-ping-default")
set_tests_properties(ctest-fd-tap-ping PROPERTIES  WORKING_DIRECTORY "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/fd-net-device/examples/CMakeLists.txt;92;build_lib_example;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/fd-net-device/examples/CMakeLists.txt;0;")
add_test(ctest-fd-tap-ping6 "ns3.42-fd-tap-ping6-default")
set_tests_properties(ctest-fd-tap-ping6 PROPERTIES  WORKING_DIRECTORY "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/fd-net-device/examples/CMakeLists.txt;101;build_lib_example;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/src/fd-net-device/examples/CMakeLists.txt;0;")
