# CMake generated Testfile for 
# Source directory: /home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/contrib/netsimulyzer/examples
# Build directory: /home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/cmake-cache/contrib/netsimulyzer/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-application-state-trace-example-netsimulyzer "ns3.42-application-state-trace-example-netsimulyzer-default")
set_tests_properties(ctest-application-state-trace-example-netsimulyzer PROPERTIES  WORKING_DIRECTORY "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build/contrib/netsimulyzer/examples/" _BACKTRACE_TRIPLES "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/contrib/netsimulyzer/examples/CMakeLists.txt;30;build_lib_example;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/contrib/netsimulyzer/examples/CMakeLists.txt;0;")
add_test(ctest-ecdf-sink-example-netsimulyzer "ns3.42-ecdf-sink-example-netsimulyzer-default")
set_tests_properties(ctest-ecdf-sink-example-netsimulyzer PROPERTIES  WORKING_DIRECTORY "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build/contrib/netsimulyzer/examples/" _BACKTRACE_TRIPLES "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/contrib/netsimulyzer/examples/CMakeLists.txt;39;build_lib_example;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/contrib/netsimulyzer/examples/CMakeLists.txt;0;")
add_test(ctest-mobility-buildings-example-netsimulyzer "ns3.42-mobility-buildings-example-netsimulyzer-default")
set_tests_properties(ctest-mobility-buildings-example-netsimulyzer PROPERTIES  WORKING_DIRECTORY "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build/contrib/netsimulyzer/examples/" _BACKTRACE_TRIPLES "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/contrib/netsimulyzer/examples/CMakeLists.txt;52;build_lib_example;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/contrib/netsimulyzer/examples/CMakeLists.txt;0;")
add_test(ctest-lena-radio-link-failure-netsimulyzer "ns3.42-lena-radio-link-failure-netsimulyzer-default")
set_tests_properties(ctest-lena-radio-link-failure-netsimulyzer PROPERTIES  WORKING_DIRECTORY "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build/contrib/netsimulyzer/examples/" _BACKTRACE_TRIPLES "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/contrib/netsimulyzer/examples/CMakeLists.txt;63;build_lib_example;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/contrib/netsimulyzer/examples/CMakeLists.txt;0;")
add_test(ctest-outdoor-random-walk-example-netsimulyzer "ns3.42-outdoor-random-walk-example-netsimulyzer-default")
set_tests_properties(ctest-outdoor-random-walk-example-netsimulyzer PROPERTIES  WORKING_DIRECTORY "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build/contrib/netsimulyzer/examples/" _BACKTRACE_TRIPLES "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/contrib/netsimulyzer/examples/CMakeLists.txt;74;build_lib_example;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/contrib/netsimulyzer/examples/CMakeLists.txt;0;")
add_test(ctest-throughput-sink-example-netsimulyzer "ns3.42-throughput-sink-example-netsimulyzer-default")
set_tests_properties(ctest-throughput-sink-example-netsimulyzer PROPERTIES  WORKING_DIRECTORY "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build/contrib/netsimulyzer/examples/" _BACKTRACE_TRIPLES "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/contrib/netsimulyzer/examples/CMakeLists.txt;85;build_lib_example;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/contrib/netsimulyzer/examples/CMakeLists.txt;0;")
add_test(ctest-wifi-bianchi-netsimulyzer "ns3.42-wifi-bianchi-netsimulyzer-default")
set_tests_properties(ctest-wifi-bianchi-netsimulyzer PROPERTIES  WORKING_DIRECTORY "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build/contrib/netsimulyzer/examples/" _BACKTRACE_TRIPLES "/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/contrib/netsimulyzer/examples/CMakeLists.txt;98;build_lib_example;/home/ns3/Desktop/project/ns-allinone-3.42/ns-3.42/contrib/netsimulyzer/examples/CMakeLists.txt;0;")
